// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVn1UoM1-UbN1CYwfb6v2ee8jEILCR3p8',
    appId: '1:845758125310:android:5337b774cfaaa8a7e781af',
    messagingSenderId: '845758125310',
    projectId: 'criptalert-187b3',
    storageBucket: 'criptalert-187b3.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaR58Yfj1FIwR8yOgRHX2rxTgD1SRjj0o',
    appId: '1:845758125310:ios:2022885acff731eee781af',
    messagingSenderId: '845758125310',
    projectId: 'criptalert-187b3',
    storageBucket: 'criptalert-187b3.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALCgErhbzvxeIlMpYt2M6wEeqVizWPl9k',
    appId: '1:845758125310:web:3c7da67f80db5bd2e781af',
    messagingSenderId: '845758125310',
    projectId: 'criptalert-187b3',
    authDomain: 'criptalert-187b3.firebaseapp.com',
    storageBucket: 'criptalert-187b3.firebasestorage.app',
    measurementId: 'G-FLDWEKK161',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaR58Yfj1FIwR8yOgRHX2rxTgD1SRjj0o',
    appId: '1:845758125310:ios:2022885acff731eee781af',
    messagingSenderId: '845758125310',
    projectId: 'criptalert-187b3',
    storageBucket: 'criptalert-187b3.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALCgErhbzvxeIlMpYt2M6wEeqVizWPl9k',
    appId: '1:845758125310:web:09aefbaf5580599de781af',
    messagingSenderId: '845758125310',
    projectId: 'criptalert-187b3',
    authDomain: 'criptalert-187b3.firebaseapp.com',
    storageBucket: 'criptalert-187b3.firebasestorage.app',
    measurementId: 'G-55CJTFPXVL',
  );

  static const FirebaseOptions linux = FirebaseOptions(
  apiKey: 'AIzaSyALCgErhbzvxeIlMpYt2M6wEeqVizWPl9k',
  appId: '1:845758125310:web:09aefbaf5580599de781af',
  messagingSenderId: '845758125310',
  projectId: 'criptalert-187b3',
  authDomain: 'criptalert-187b3.firebaseapp.com',
  storageBucket: 'criptalert-187b3.firebasestorage.app',
  measurementId: 'G-55CJTFPXVL',
);
}
