name: mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  
  flutter_svg: ^2.0.0

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  provider: ^6.1.2
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.2.2
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  ulid: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.14.3

flutter:
  assets:
    - assets/Logo/
    - assets/Icons/
    - assets/Presentation/
    
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

flutter_native_splash:
  color: "#000000"
  image: assets/Logo/CriptAlert.png
  color_dark: "#000000"
  image_dark: assets/Logo/CriptAlert.png
  android_12:
    color: "#000000"
    icon_background_color: "#000000"
    image: assets/Logo/CriptAlert.png
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Logo/CriptAlert.png"
  # opcional: ícone adaptativo Android (fundo colorido)
  adaptive_icon_background: "#0D0D0D"
  adaptive_icon_foreground: "assets/Logo/CriptAlert.png"